from src.database.models import Chain, MenuItem


chains = [
	Chain(name="2x2", description="Pasta bar with the bad pasta."),
	Chain(name="Night and Day", description="Pizza, pasta and everything else place."),
	Chain(name="Viljuskica Rajkova", description="Raspolozeni ste za domacu hranu."),
	Chain(name="Druzina Rostiljko", description="Rostilj i jos po nesto."),
	Chain(name="Kafeterija", description="Coffee place."),
	Chain(name="Pekara Brankovic", description="Jako stara pekara u nisu."),
	Chain(name="Pekara Bata Bane", description="Sveza peciva uvek."),
	Chain(name="IDEA", description="Expensive supermarket."),
	Chain(name="Pekara Bata Bane", description=".")
]

foods = [
	("2x2", MenuItem(name='Carbonara', 
				description="Bacon, eggs, spices and few other things.",
				price=600,
				currency="RSD",
				imgUrl="https://www.laboiteny.com/cdn/shop/articles/carbonara.jpg?v=1617745985")),
	("2x2", MenuItem(name='Bolognese', 
				description="Tomato, beef and spices.",
				price=620,
				currency="RSD",
				imgUrl="https://schoolnightvegan.com/wp-content/uploads/2022/02/vegan-bolognese-17.jpg")),
	("2x2", MenuItem(name='Tuna Sallad', 
				description="Cold pasta with some pene and tunna",
				price=400,
				currency="RSD",
				imgUrl="https://healthyfitnessmeals.com/wp-content/uploads/2019/11/instagram-In-Stream_Square___Creamy-tuna-pasta-salad-2.jpg")),
	("2x2", MenuItem(name='Pollo e Pesto', 
				description="Pesto sauce with chicken meat.",
				price=440,
				currency="RSD",
				imgUrl="https://ik.imagekit.io/misterd/tr:w-500,q-90/photo/_g70vtxx1wheagw6_1656107730339_Pollo%20e%20Pesto.jpg")),
	("2x2", MenuItem(name='Pollo e Pesto', 
				description="Pesto sauce with chicken meat.",
				price=440,
				currency="RSD",
				imgUrl="https://ik.imagekit.io/misterd/tr:w-500,q-90/photo/_g70vtxx1wheagw6_1656107730339_Pollo%20e%20Pesto.jpg")),				
	("Night and Day", MenuItem(name='Napolitana', 
				description="Basic pizza, tomato and spices",
				price=440,
				currency="RSD",
				imgUrl="https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg")),
	("Night and Day", MenuItem(name='Perfetta', 
				description="Tomato, some vegetablesn and goat chees.",
				price=350,
				currency="RSD",
				imgUrl="https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg")),
	("Night and Day", MenuItem(name='Quattro Formaggi', 
				description="Four cheese pizza",
				price=600,
				currency="RSD",
				imgUrl="https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg")),
	("Night and Day", MenuItem(name='Capricosa', 
				description="Tomato sauce, some ham anc chees.",
				price=400,
				currency="RSD",
				imgUrl="https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg")),
	("Night and Day", MenuItem(name='Vesuvio', 
				description="Spicy one.",
				price=520,
				currency="RSD",
				imgUrl="https://upload.wikimedia.org/wikipedia/commons/9/91/Pizza-3007395.jpg")),
	("Night and Day", MenuItem(name='Chicken sandwich', 
				description="Sandwich with chicken meat and some sauce.",
				price=330,
				currency="RSD",
				imgUrl="https://twocloveskitchen.com/wp-content/uploads/2024/01/Grinder-Sandwich-whole-1.jpg")),
	("Night and Day", MenuItem(name='Tunna sandwich', 
				description="Sandwich with tunna and some sauce.",
				price=300,
				currency="RSD",
				imgUrl="https://twocloveskitchen.com/wp-content/uploads/2024/01/Grinder-Sandwich-whole-1.jpg")),
	("Night and Day", MenuItem(name='Nutella Pancake', 
				description="Pancake with some nutella in it.",
				price=330,
				currency="RSD",
				imgUrl="https://40204166.fs1.hubspotusercontent-na1.net/hub/40204166/hubfs/New%20Recipe%20images/Sunday%20Pancakes%20Recipe%20NZ%20Chelsea%20Sugar.jpg?width=755&height=500&name=Sunday%20Pancakes%20Recipe%20NZ%20Chelsea%20Sugar.jpg")),
	("Night and Day", MenuItem(name='Honey Pancake', 
				description="Pancake with some honey in it.",
				price=400,
				currency="RSD",
				imgUrl="https://40204166.fs1.hubspotusercontent-na1.net/hub/40204166/hubfs/New%20Recipe%20images/Sunday%20Pancakes%20Recipe%20NZ%20Chelsea%20Sugar.jpg?width=755&height=500&name=Sunday%20Pancakes%20Recipe%20NZ%20Chelsea%20Sugar.jpg")),

]
